services:
  comfyui-m2:
    build:
      context: .
      dockerfile: Dockerfile.arm64
    platform: linux/arm64
    container_name: comfyui-m2
    restart: unless-stopped
    ports:
      - "8188:8188"
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
      - CUDA_VISIBLE_DEVICES=""
    volumes:
      # Model directories - mount to persist models between container restarts
      - ./models:/app/models
      # Input and output directories
      - ./input:/app/input
      - ./output:/app/output
      # Custom nodes directory
      - ./custom_nodes:/app/custom_nodes
      # User directory for configurations
      - ./user:/app/user
      # Temp directory (optional, can be omitted to use container temp)
      - ./temp:/app/temp
      # Optional: Mount extra model paths configuration
      - ./extra_model_paths.yaml:/app/extra_model_paths.yaml:ro
    # Resource limits for M2 Max
    deploy:
      resources:
        limits:
          memory: 32G  # M2 Max can handle more memory
          cpus: '12'   # M2 Max has 12 CPU cores
    networks:
      - comfyui-network

networks:
  comfyui-network:
    driver: bridge
