name: ComfyUI-cpu

services:
  comfyui-cpu:
    build: 
      context: .
      dockerfile: Dockerfile.cpu
    container_name: comfyui-cpu
    restart: unless-stopped
    ports:
      - "8188:8188"
    volumes:
      # Model directories - mount to persist models between container restarts
      - ./models:/app/models
      # Input and output directories
      - ./input:/app/input
      - ./output:/app/output
      # Custom nodes directory
      - ./custom_nodes:/app/custom_nodes
      # User directory for configurations
      - ./user:/app/user
      # Temp directory (optional, can be omitted to use container temp)
      - ./temp:/app/temp
      # Optional: Mount extra model paths configuration
      - ./extra_model_paths.yaml:/app/extra_model_paths.yaml:ro
    command: ["python3", "main.py", "--listen", "0.0.0.0", "--port", "8188", "--cpu"]
    networks:
      - comfyui-network

networks:
  comfyui-network:
    driver: bridge
